# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('bonus', models.FloatField(default=0, verbose_name='奖金')),
                ('is_active', models.BooleanField(default=False, verbose_name='状态')),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'bonus',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('investment_eth', models.CharField(default=0, max_length=20, verbose_name='投资数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'vm_information',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('invite_num', models.CharField(blank=True, max_length=5, null=True, verbose_name='邀请码')),
                ('invite_num_son', models.CharField(blank=True, max_length=5, null=True, verbose_name='邀请码')),
                ('eth', models.CharField(default=0, max_length=20, verbose_name='投资数量')),
                ('purse_addr', models.CharField(max_length=42, unique=True, verbose_name='钱包地址')),
                ('is_staff', models.BooleanField(default=False, verbose_name='权限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
